"""
cashflows.py

Core cash flow generation and accrual functions for BondPricer.
- Generate coupon schedules and cash flow series for bonds
- Compute accrued interest and support BondInput class

Functions: coupon_schedule, bond_cash_flows, generate_coupon_dates, generate_cash_flows, compute_accrued_interest

Author: Fatima Ezzahra Jabiri
Created: 2026-02-22
"""
import numpy as np
import pandas as pd
import math
from datetime import datetime
from src.discount_utils import * 

 

def coupon_schedule(settlement_date, maturity_date, coupon_days, principal = 100, coupon_rate = 0.0, freq = 2):

        """
        Returns the schedule of coupon and principal payments for a bond as a Series indexed by payment date.
        """
        if len(coupon_days) != freq:
            raise ValueError(f"Length of {coupon_days} does not match {freq}. ")
        else:
            schedule = {}
            coupon_amt = principal * coupon_rate / freq
            set_day = pd.to_datetime(settlement_date)
            mat_day = pd.to_datetime(maturity_date)
            for year in range(set_day.year, mat_day.year + 1):
                for mmdd in coupon_days:
                    coupon_date = pd.to_datetime(f"{year}-{mmdd}")
                    if set_day < coupon_date <= mat_day:
                        schedule[coupon_date] = coupon_amt
            # Add principal at maturity
            if mat_day in schedule:
                schedule[mat_day] += principal
            else:
                schedule[mat_day] = principal
            # Return as a sorted Series for clarity
            return pd.Series(schedule).sort_index()


# Poor's man bond pricing
def bond_cash_flows(maturity, principal=100, coupon_rate=0.03, freq=12):
    """
    Returns the series of cash flows generated by a bond including the principal. 
    indexed by the payment/coupon number
    """
    n_coupons = round(maturity*freq)
    coupon_amt = principal*coupon_rate/freq
    coupon_times = np.arange(1, n_coupons+1)
    cash_flows = pd.DataFrame({'cash_flow': coupon_amt}, index=coupon_times)
    cash_flows.iloc[-1, cash_flows.columns.get_loc('cash_flow')] += principal 
    cash_flows['time_years'] = cash_flows.index / freq
    return cash_flows




